### ISSUE TITLE
lock page problem 

### ISSUE THREAD

**Issue by Hwiii0610** [creativetimofficial/ct-paper-dashboard-pro-angular#2]
please help . 

landscape mode problem. 

<img width="629" alt="2017-09-14 1 56 23" src="https://user-images.githubusercontent.com/16669599/30412994-8ddfac8a-9956-11e7-8272-4462055266d0.png">

regards.

**Comment by dragosct** [comment]
Hi @YeoDaeHwi! The issue on the landscape mode can be fixed by simple going in your project in `assets/sass/paper/_pages.scss` and inside of this partial please search for the following lines of code: 

```css
.lock-page{
     .card-lock{
        text-align: center;
        width: 300px;
        margin: 30px auto 0;
        padding: 30px;
        position: absolute;
        left: 50%;
        margin-left: -150px;
        display: block;
     }
}
``` 
Now please remove the properties: `position: absolute;`, `display: block;`, `text-align: center;`. After you do that please compile your scss with [Koala](http://koala-app.com/) and be sure that your output path is `assets/css/paper-dashboard.css`.

Hope that will help you! 

Regards,
Dragos
